trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'MyApp'
  buildTagCompile: ${{ format('v1.0.{0}', variables['Build.BuildId']) }} # compile-time
  buildTagRuntime: "v1.0.$(Build.BuildId)"                              # runtime

steps:
  # STEP 1 - Show compile-time vs runtime variables
  - script: |
      echo "===== STEP 1: Variable Evaluation ====="
      echo "Compile-time tag (evaluated before run): ${{ variables.buildTagCompile }}"
      echo "Runtime tag (evaluated during run): $(buildTagRuntime)"
    displayName: "Compare compile-time vs runtime"

  # STEP 2 - Generate a runtime variable using a logging command
  - script: |
      echo "===== STEP 2: Creating dynamic runtime variable ====="
      echo "##vso[task.setvariable variable=dynamicTag]Dynamic-$(Build.BuildId)-$(appName)"
    displayName: "Create dynamic variable"

  # STEP 3 - Use the dynamic variable created in Step 2
  - script: |
      echo "===== STEP 3: Using runtime variable created dynamically ====="
      echo "Dynamic variable value: $(dynamicTag)"
    displayName: "Use dynamic variable"

  # STEP 4 - Bonus: print all environment variables for inspection
  - script: |
      echo "===== STEP 4: Listing environment variables ====="
      env | sort
    displayName: "Inspect environment variables"
