trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'MyApp'
  buildTagCompile: ${{ format('v1.0.{0}', variables['Build.BuildId']) }} # compile-time
  buildTagRuntime: "v1.0.$(Build.BuildId)"
  compilevar: "alvaro"
  CurrentDateTime: "$(Get-Date -Format yyyy.MM.dd_HHmmss)"                        # runtime

steps:
  # STEP 1 - Show compile-time vs runtime variables
  - script: |
      echo "===== STEP 1: Variable Evaluation ====="
      echo "Compile-time tag (evaluated before run): ${{ variables.compilevar }}"
    displayName: "Show compile-time variable"

  - script: |
     echo "Runtime tag (evaluated during run): $(buildTagRuntime)"
    displayName: "Show runtime variable"

  # STEP 2 - Generate a runtime variable using a logging command
  - script: |
      echo "===== STEP 2: Creating dynamic runtime variable ====="
      echo "##vso[task.setvariable variable=dynamicTag]Createdynamicvar-$(Build.BuildId)-$(compilevar)-$(CurrentDateTime)"
    displayName: "Create dynamic variable"

  # STEP 3 - Use the dynamic variable created in Step 2
  - script: |
      echo "===== STEP 3: Using runtime variable created dynamically ====="
      echo "Dynamic variable value: $(dynamicTag)"
    displayName: "Use dynamic variable"
