trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
   - script: echo "Run script in Azure devops pipeline"
     displayName: "Run a one-line script"

   - script: pwd && ls -la
     displayName: "List workspace"