trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: "MyApp"
  env: "Production"

## ${{ variables.var }} its use for compile logic and template
## $(var) its use for runtime values
steps:
  #  - script: echo "Deploying $(appName) to ${{variables.env}} environment"
  #    displayName: "Deployment with variable and outputs"

  #  - script: echo "Using secret key $(SECRETKEY)"
  #    displayName: "Using environment variable"
   - script: |
      echo "Deploying $(appName) to $(env) environment"
     displayName: "Print variables (macro syntax)"