trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: "MyApp"
  env: "Production"
  secretkey: "$(SECRETKEY)"

steps:
   - script: echo "Deploying $(appName) to $(env) environment"
     displayName: "Deployment with variable and outputs"

   - script: echo "Using secret key $(SECRETKEY)"
     displayName: "Using environment variable"